### ISSUE TITLE
[EPIC] Plan of Action for Workbench/Database Optimization

### ISSUE THREAD

**Issue by jarmoza** [printprobability/printprob-db#70]
The following is plan of action for speeding up and optimizing the database, IIIF server, and workbench (produced via a meeting between @jrladd, @kartikgo, and myself on December 14, 2023).

**Partitioning**

- [ ] 1. Inquire about Sriram's previous Postgres partitioning ideas at meeting with him
- [ ] 2. How is partitioning implemented in Postgres and are there multiple possible implementations/options?
- [ ] 3. How will partitioning affect Django code if at all?

**IIIF**

- [ ] 1. How much time is IIIF serving of images taking in the requests?
- [ ] 2. IIIF background research
- [ ] 3. Asking Matt Lincoln (via email) about potential serving speedups

**Request Times**

- [ ] 1. Creating a clear diagram of how requests are processed from workbench website to django to postgres and then back up
- [ ] 2. Getting a clear idea of typical timestamps for each of these processes if not their subprocesses
- [ ] 3. Diagram so it's clear to all how our websiste/workbench is working/processing requests
- [ ] 4. What time does Django processing/serialization take, for instance?
